/// Generated by AssetsRefGenerator on 2020/03/15
class Res {
  static const String ic_main_tab_company_nor = "images/ic_main_tab_company_nor.png";
  static const String ic_main_tab_company_pre = "images/ic_main_tab_company_pre.png";
  static const String ic_main_tab_contacts_nor = "images/ic_main_tab_contacts_nor.png";
  static const String ic_main_tab_contacts_pre = "images/ic_main_tab_contacts_pre.png";
  static const String ic_main_tab_find_nor = "images/ic_main_tab_find_nor.png";
  static const String ic_main_tab_find_pre = "images/ic_main_tab_find_pre.png";
  static const String ic_main_tab_my_nor = "images/ic_main_tab_my_nor.png";
  static const String ic_main_tab_my_pre = "images/ic_main_tab_my_pre.png";









}
